server:
  port: 9001
spring:
  application:
    name: quiet-scrum
  profiles:
    active: resource-server-dev
security:
  oauth2:
    client:
      client-secret: quiet
dubbo:
  cloud:
    subscribed-services: quiet-system
  scan:
    base-packages: com.gitee.quiet.scrum.service