server:
  port: 9010
spring:
  application:
    name: quiet-scrum
  profiles:
    active: dev
  config:
    import: classpath:application-resource-server.yaml
security:
  oauth2:
    client:
      client-secret: quiet-scrum
dubbo:
  cloud:
    subscribed-services: quiet-system
  scan:
    base-packages: com.gitee.quiet.scrum.service
quiet:
  id-generator:
    worker-id: 1
    data-center-id: 0