spring:
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/quiet?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root93633
    hikari:
      connection-timeout: 30000
      idle-timeout: 300000
      pool-name: jpa-hikari-pool
      max-lifetime: 900000
      maximum-pool-size: 12
      minimum-idle: 8
      connection-test-query: select 1 from dual
      auto-commit: true
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/quiet?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root93633
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace