dubbo:
  registry:
    address: nacos://127.0.0.1:8848/?username=nacos&password=nacos
---
spring:
  config:
    activate:
      on-profile: dev
dubbo:
  registry:
    address: nacos://127.0.0.1:8848/?username=nacos&password=nacos