spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848