server:
  port: 9020
spring:
  application:
    name: quiet-doc
  profiles:
    active: dev
  config:
    import: optional:classpath:application-resource-server.yaml
security:
  oauth2:
    client:
      client-secret: quiet-doc
dubbo:
  registry:
    address: nacos://127.0.0.1:8848/?username=nacos&password=nacos
  scan:
    base-packages: com.gitee.quiet.doc.service
quiet:
  jpa:
    id-generator:
      worker-id: 2
      data-center-id: 0