spring:
  application:
    name: quiet-gateway
  profiles:
    active: dev
  config:
    import:
      - classpath:application-redis.yaml
      - classpath:application-registry.yaml
      - classpath:application-routes.yaml