spring:
  application:
    name: quiet-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: system
          uri: lb://quiet-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1