spring:
  profiles:
    active: dev
  config:
    import: classpath:application-mysql.yaml,classpath:application-redis.yaml,classpath:application-registry.yaml
---
spring:
  config:
    activate:
      on-profile: dev
    import: classpath:application-mysql.yaml,classpath:application-redis.yaml,classpath:application-registry.yaml
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace