spring:
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    locale: zh_CN
    time-zone: GMT+8
security:
  oauth2:
    client:
      client-id: ${spring.application.name}
    resource:
      id: ${spring.application.name}
dubbo:
  protocol:
    port: -1
    id: dubbo
    name: dubbo
  consumer:
    check: false
    filter: token-value-consumer
  provider:
    filter: token-value-provider
quiet:
  id-generator:
    max-server-number: 10