spring:
  config:
    import: classpath:application-all.yaml
security:
  oauth2:
    client:
      access-token-uri: http://localhost:9000/oauth/token
      user-authorization-uri: http://localhost:9000/oauth/authorize
    resource:
      user-info-uri: http://localhost:9000/oauth/oauth_user
    authorization:
      check-token-access: http://localhost:9000/oauth/check_token
---
spring:
  config:
    activate:
      on-profile: dev
security:
  oauth2:
    client:
      access-token-uri: http://localhost:9000/oauth/token
      user-authorization-uri: http://localhost:9000/oauth/authorize
    resource:
      user-info-uri: http://localhost:9000/oauth/oauth_user
    authorization:
      check-token-access: http://localhost:9000/oauth/check_token