server:
  port: 9000
spring:
  application:
    name: quite-system
  datasource:
    url: jdbc:mysql://localhost:3306/quite?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root93633
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    locale: zh_CN
    time-zone: GMT+8