spring:
  application:
    name: quiet-system
  profiles:
    active: dev
  config:
    import: classpath:application-all.yaml
server:
  port: 9000
dubbo:
  scan:
    base-packages: com.gitee.quiet.system.service
  registry:
    address: nacos://127.0.0.1:8848/?username=nacos&password=nacos
quiet:
  jpa:
    id-generator:
      worker-id: 0
      data-center-id: 0