spring:
  application:
    name: quiet-system
  profiles:
    active: dev
  config:
    import: optional:classpath:application-all.yaml
server:
  port: 9000
dubbo:
  scan:
    base-packages: com.gitee.quiet.system.service
quiet:
  jpa:
    id-generator:
      worker-id: 0
      data-center-id: 0