spring:
  application:
    name: quiet-system
  profiles:
    active: dev
  config:
    import: classpath:application-all.yaml
server:
  port: 9000
dubbo:
  scan:
    base-packages: com.gitee.quiet.system.service
  cloud:
    subscribed-services:
quiet:
  id-generator:
    worker-id: 0
    data-center-id: 0